export const DETAIL_NAMESPACE = 'DETAIL';

export const DETAIL_ACTION_TYPES = {
    DETAILS_REQUESTED: `${DETAIL_NAMESPACE}/DETAILS_REQUESTED`,
    DETAILS_RECEIVED: `${DETAIL_NAMESPACE}/DETAILS_RECEIVED`,
    DETAILS_CLEARED: `${DETAIL_NAMESPACE}/DETAILS_CLEARED`,
};